In [1]:
import pandas as pd
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.model_selection import cross_val_score

D:\Users\cccc\anaconda3\Lib\site-packages\pandas\core\computation\expressions.py:23: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED


In [12]:
!pip install --upgrade scikit-learn mlxtend

  Using cached mlxtend-0.25.0-py3-none-any.whl.metadata (7.4 kB)
Using cached mlxtend-0.25.0-py3-none-any.whl (1.4 MB)


In [2]:
df = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vQDVwxneOKOaJL13QMhkAhYrgWlH1tICY7RacUnj_lL8m9uUWaaUf3p7bScNyh_D2Rvt7nc1q11adSy/pub?gid=647503637&single=true&output=csv')

In [3]:
df.head()

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,white,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,white,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,white,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,white,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,white,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6


In [4]:
df.isnull().sum()

type                     0
fixed acidity           10
volatile acidity         8
citric acid              3
residual sugar           2
chlorides                2
free sulfur dioxide      0
total sulfur dioxide     0
density                  0
pH                       9
sulphates                4
alcohol                  0
quality                  0
dtype: int64

In [5]:
df.drop(columns=['type','fixed acidity','volatile acidity'],inplace=True)

In [6]:
df.dropna(inplace=True)

In [7]:
df.isnull().sum()

citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,:-1], df['quality'], test_size=0.2, random_state=1)

In [9]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [54]:
import numpy as np
from sklearn.metrics import r2_score
model = LogisticRegression()


print("training",np.mean(cross_val_score(model, X_train, y_train, cv=5, scoring='accuracy')))
print("testing",np.mean(cross_val_score(model, X_test, y_test, cv=5, scoring='accuracy')))

D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the n

training 0.5321379238447705
testing 0.516991386991387


D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(


In [22]:
X_train

array([[ 0.21752121,  0.24035722, -0.77660867, ...,  0.44064869,
        -0.61568968,  1.68094926],
       [ 0.28692491, -0.76471144, -0.63192136, ...,  1.24563422,
         1.05693094,  0.42217209],
       [ 1.81380643, -0.27286933,  1.04645149, ...,  0.44064869,
         3.06407569,  1.26135687],
       ...,
       [ 0.1481175 ,  0.75358377, -0.22679688, ...,  0.19296084,
         0.05335857,  0.42217209],
       [-0.61532326,  1.78003687, -0.16892195, ..., -0.11664898,
        -0.48188003, -1.5079529 ],
       [-0.96234178,  0.34727942,  0.93070164, ...,  0.99794636,
         1.59216954, -0.92052356]], shape=(5181, 9))

In [23]:
from mlxtend.feature_selection import ExhaustiveFeatureSelector as EFS

lr = LogisticRegression()

sel = EFS(lr, max_features=9, scoring='accuracy', cv=5)

In [24]:
model = sel.fit(X_train, y_train)

D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-pa

In [25]:
model.best_score_

np.float64(0.5321379238447705)

In [26]:
model.best_feature_names_

('0', '1', '2', '3', '4', '5', '6', '7', '8')

In [27]:
model.subsets_

{0: {'feature_idx': (0,),
  'cv_scores': array([0.43972999, 0.44401544, 0.44305019, 0.43918919, 0.43918919]),
  'avg_score': np.float64(0.4410348011601628),
  'feature_names': ('0',)},
 1: {'feature_idx': (1,),
  'cv_scores': array([0.43876567, 0.44208494, 0.43918919, 0.43822394, 0.43918919]),
  'avg_score': np.float64(0.43949058577795314),
  'feature_names': ('1',)},
 2: {'feature_idx': (2,),
  'cv_scores': array([0.45708775, 0.44401544, 0.44401544, 0.45366795, 0.45945946]),
  'avg_score': np.float64(0.4516492108584684),
  'feature_names': ('2',)},
 3: {'feature_idx': (3,),
  'cv_scores': array([0.43972999, 0.44015444, 0.43918919, 0.43918919, 0.43918919]),
  'avg_score': np.float64(0.43949039961576125),
  'feature_names': ('3',)},
 4: {'feature_idx': (4,),
  'cv_scores': array([0.43972999, 0.43918919, 0.44015444, 0.43822394, 0.44015444]),
  'avg_score': np.float64(0.43949039961576125),
  'feature_names': ('4',)},
 5: {'feature_idx': (5,),
  'cv_scores': array([0.45515911, 0.44015444, 

In [28]:
metric_df = pd.DataFrame.from_dict(model.get_metric_dict()).T

In [29]:
metric_df

,feature_idx,cv_scores,avg_score,feature_names,ci_bound,std_dev,std_err
0,"(0,)","[0.43972999035679844, 0.444015444015444, 0.443...",0.441035,"(0,)",0.002663,0.002072,0.001036
1,"(1,)","[0.43876567020250723, 0.4420849420849421, 0.43...",0.439491,"(1,)",0.001728,0.001345,0.000672
2,"(2,)","[0.4570877531340405, 0.444015444015444, 0.4440...",0.451649,"(2,)",0.008353,0.006499,0.00325
3,"(3,)","[0.43972999035679844, 0.44015444015444016, 0.4...",0.43949,"(3,)",0.000505,0.000393,0.000196
4,"(4,)","[0.43972999035679844, 0.4391891891891892, 0.44...",0.43949,"(4,)",0.000933,0.000726,0.000363
...,...,...,...,...,...,...,...
506,"(0, 1, 2, 4, 5, 6, 7, 8)","[0.5207328833172613, 0.5144787644787645, 0.534...",0.524224,"(0, 1, 2, 4, 5, 6, 7, 8)",0.009257,0.007202,0.003601
507,"(0, 1, 3, 4, 5, 6, 7, 8)","[0.5265188042430087, 0.5222007722007722, 0.538...",0.528856,"(0, 1, 3, 4, 5, 6, 7, 8)",0.007025,0.005466,0.002733
508,"(0, 2, 3, 4, 5, 6, 7, 8)","[0.5390549662487946, 0.5144787644787645, 0.516...",0.524799,"(0, 2, 3, 4, 5, 6, 7, 8)",0.012011,0.009345,0.004672
509,"(1, 2, 3, 4, 5, 6, 7, 8)","[0.5226615236258437, 0.527027027027027, 0.5347...",0.526154,"(1, 2, 3, 4, 5, 6, 7, 8)",0.011102,0.008637,0.004319


In [68]:
X_train_sel = sel.transform(X_train)
X_test_sel = sel.transform(X_test)

In [69]:
X_train_sel

array([[ 0.21752121,  0.24035722, -0.77660867, ...,  0.44064869,
        -0.61568968,  1.68094926],
       [ 0.28692491, -0.76471144, -0.63192136, ...,  1.24563422,
         1.05693094,  0.42217209],
       [ 1.81380643, -0.27286933,  1.04645149, ...,  0.44064869,
         3.06407569,  1.26135687],
       ...,
       [ 0.1481175 ,  0.75358377, -0.22679688, ...,  0.19296084,
         0.05335857,  0.42217209],
       [-0.61532326,  1.78003687, -0.16892195, ..., -0.11664898,
        -0.48188003, -1.5079529 ],
       [-0.96234178,  0.34727942,  0.93070164, ...,  0.99794636,
         1.59216954, -0.92052356]], shape=(5181, 9))

In [55]:
model = LogisticRegression()

print("training",np.mean(cross_val_score(model, X_train_sel, y_train, cv=5, scoring='accuracy')))
print("testing",np.mean(cross_val_score(model, X_test_sel, y_test, cv=5, scoring='accuracy')))

D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the n

training 0.5321379238447705
testing 0.516991386991387


D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(


### Sequential Backward Elimination

In [56]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from mlxtend.feature_selection import SequentialFeatureSelector as SFS

# load the dataset
df = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vQDVwxneOKOaJL13QMhkAhYrgWlH1tICY7RacUnj_lL8m9uUWaaUf3p7bScNyh_D2Rvt7nc1q11adSy/pub?gid=647503637&single=true&output=csv')

df.drop(columns=['type','fixed acidity','volatile acidity'],inplace=True)

df.dropna(inplace=True)

# separate the target variable
X = df.drop("quality", axis=1)
y = df['quality']


# split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

print(X_train.shape)

(5181, 9)


In [57]:
sfs = SFS(lr, k_features='best', forward=False, floating=False, scoring='r2',cv=5)

sfs.fit(X_train, y_train)

D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the n

,estimator,LogisticRegression()
,k_features,"(1, ...)"
,forward,False
,scoring,'r2'
,floating,False
,verbose,0
,cv,5
,n_jobs,1
,pre_dispatch,'2*n_jobs'
,clone_estimator,True
,fixed_features,None


In [58]:
sfs.k_feature_idx_

(0, 1, 3, 4, 5, 6, 7, 8)

In [59]:
metric_df = pd.DataFrame.from_dict(sfs.get_metric_dict()).T

In [60]:
metric_df

,feature_idx,cv_scores,avg_score,feature_names,ci_bound,std_dev,std_err
9,"(0, 1, 2, 3, 4, 5, 6, 7, 8)","[0.06743685263479493, 0.11482192109365619, 0.1...",0.104678,"(0, 1, 2, 3, 4, 5, 6, 7, 8)",0.027204,0.021166,0.010583
8,"(0, 1, 3, 4, 5, 6, 7, 8)","[0.08659910908750468, 0.09670424111604092, 0.1...",0.108712,"(0, 1, 3, 4, 5, 6, 7, 8)",0.028245,0.021975,0.010988
7,"(0, 1, 3, 4, 5, 7, 8)","[0.06743685263479493, 0.0876454011272334, 0.14...",0.098737,"(0, 1, 3, 4, 5, 7, 8)",0.032675,0.025422,0.012711
6,"(1, 3, 4, 5, 7, 8)","[0.058494466290197056, 0.11352780109525507, 0....",0.087075,"(1, 3, 4, 5, 7, 8)",0.028954,0.022527,0.011264
5,"(1, 3, 4, 7, 8)","[0.05593949876316906, 0.1018807211096453, 0.12...",0.083475,"(1, 3, 4, 7, 8)",0.042913,0.033388,0.016694
4,"(1, 3, 7, 8)","[0.04827459618208518, 0.11482192109365619, 0.1...",0.084531,"(1, 3, 7, 8)",0.049285,0.038345,0.019173
3,"(3, 7, 8)","[0.05593949876316906, 0.0811748011352279, 0.10...",0.077799,"(3, 7, 8)",0.028278,0.022001,0.011
2,"(3, 8)","[0.053384531236141175, 0.04882180117520074, 0....",0.055008,"(3, 8)",0.026851,0.020891,0.010445
1,"(8,)","[0.02272492091180567, 0.059174761162409384, 0....",0.054009,"(8,)",0.032665,0.025415,0.012707


In [61]:
X_train_sel = sfs.transform(X_train)
X_test_sel = sfs.transform(X_test)

model = LogisticRegression()

print("training",np.mean(cross_val_score(model, X_train_sel, y_train, cv=5, scoring='accuracy')))
print("testing",np.mean(cross_val_score(model, X_test_sel, y_test, cv=5, scoring='accuracy')))

D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(


training 0.5288558844007252
testing 0.5177517077517078


D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(


# Forward Selection

In [62]:
sfs = SFS(lr, k_features='best', forward=True, floating=False, scoring='r2',cv=5)

sfs.fit(X_train, y_train)

D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-pa

,estimator,LogisticRegression()
,k_features,"(1, ...)"
,scoring,'r2'
,forward,True
,floating,False
,verbose,0
,cv,5
,n_jobs,1
,pre_dispatch,'2*n_jobs'
,clone_estimator,True
,fixed_features,None


In [63]:
sfs.k_feature_idx_

(0, 1, 2, 3, 4, 5, 6, 7, 8)

In [64]:
metric_df = pd.DataFrame.from_dict(sfs.get_metric_dict()).T

In [65]:
metric_df

,feature_idx,cv_scores,avg_score,feature_names,ci_bound,std_dev,std_err
1,"(8,)","[0.02272492091180567, 0.059174761162409384, 0....",0.054009,"(8,)",0.032665,0.025415,0.012707
2,"(2, 8)","[0.059771950053711054, 0.07729244114002465, 0....",0.074208,"(2, 8)",0.037075,0.028845,0.014423
3,"(2, 7, 8)","[0.046997112418571296, 0.09023364112403554, 0....",0.07731,"(2, 7, 8)",0.036738,0.028583,0.014292
4,"(1, 2, 7, 8)","[0.05210704747262718, 0.12129252108566169, 0.0...",0.088105,"(1, 2, 7, 8)",0.039709,0.030895,0.015448
5,"(1, 2, 6, 7, 8)","[0.053384531236141175, 0.11741016109045832, 0....",0.091663,"(1, 2, 6, 7, 8)",0.044409,0.034552,0.017276
6,"(0, 1, 2, 6, 7, 8)","[0.06999182016182293, 0.09799836111444205, 0.1...",0.096709,"(0, 1, 2, 6, 7, 8)",0.040078,0.031182,0.015591
7,"(0, 1, 2, 5, 6, 7, 8)","[0.05593949876316906, 0.09929248111284317, 0.1...",0.097486,"(0, 1, 2, 5, 6, 7, 8)",0.036383,0.028307,0.014154
8,"(0, 1, 2, 4, 5, 6, 7, 8)","[0.059771950053711054, 0.08893952112563441, 0....",0.096174,"(0, 1, 2, 4, 5, 6, 7, 8)",0.029596,0.023027,0.011514
9,"(0, 1, 2, 3, 4, 5, 6, 7, 8)","[0.06743685263479493, 0.11482192109365619, 0.1...",0.104678,"(0, 1, 2, 3, 4, 5, 6, 7, 8)",0.027204,0.021166,0.010583


In [67]:
X_train_sel = sfs.transform(X_train)
X_test_sel = sfs.transform(X_test)

model = LogisticRegression()

print("training",np.mean(cross_val_score(model, X_train_sel, y_train, cv=5, scoring='accuracy')))
print("testing",np.mean(cross_val_score(model, X_test_sel, y_test, cv=5, scoring='accuracy')))

D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the n

training 0.5321379238447705
testing 0.516991386991387


D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(


## Using sklearn

In [83]:
from sklearn.feature_selection import SequentialFeatureSelector as SFS


sfs2 = SFS(model,
           n_features_to_select=5,
           direction='forward',
           scoring='r2',
           n_jobs=-1,
           cv=5)

sfs2 = sfs2.fit(X_train, y_train)

D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
D:\Users\cccc\anaconda3\Lib\site-pa

In [88]:
np.arange(X_train.shape[1])[sfs2.support_]

array([0, 3, 6, 7, 8])

# Recursive Feature Selection

In [72]:
df = pd.read_csv('https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv')
df.head()

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa


In [73]:
X = df.iloc[:,0:-1]
y = df.iloc[:,-1]

In [74]:
X.head()

,sepal_length,sepal_width,petal_length,petal_width
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,4.7,3.2,1.3,0.2
3,4.6,3.1,1.5,0.2
4,5.0,3.6,1.4,0.2


In [75]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()

rf.fit(X,y)

,"n_estimators n_estimators: int, default=100The number of trees in the forest... versionchanged:: 0.22 The default value of ``n_estimators`` changed from 10 to 100 in 0.22.",100
,"criterion criterion: {""gini"", ""entropy"", ""log_loss""}, default=""gini""The function to measure the quality of a split. Supported criteria are""gini"" for the Gini impurity and ""log_loss"" and ""entropy"" both for theShannon information gain, see :ref:`tree_mathematical_formulation`.Note: This parameter is tree-specific.",'gini'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",None
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: {""sqrt"", ""log2"", None}, int or float, default=""sqrt""The number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None, then `max_features=n_features`... versionchanged:: 1.1 The default of `max_features` changed from `""auto""` to `""sqrt""`.Note: the search for a split does not stop until at least onevalid partition of the node samples is found, even if it requires toeffectively inspect more than ``max_features`` features.",'sqrt'
,"max_leaf_nodes max_leaf_nodes: int, default=NoneGrow trees with ``max_leaf_nodes`` in best-first fashion.Best nodes are defined as relative reduction in impurity.If None then unlimited number of leaf nodes.",None
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total number of samples, ``N_t`` is the number ofsamples at the current node, ``N_t_L`` is the number of samples in theleft child, and ``N_t_R`` is the number of samples in the right child.``N``, ``N_t``, ``N_t_R`` and ``N_t_L`` all refer to the weighted sum,if ``sample_weight`` is passed... versionadded:: 0.19",0.0
,"bootstrap bootstrap: bool, default=TrueWhether bootstrap samples are used when building trees. If False, thewhole dataset is used to build each tree.",True
,"oob_score oob_score: bool or callable, default=FalseWhether to use out-of-bag samples to estimate the generalization score.By default, :func:`~sklearn.metrics.accuracy_score` is used.Provide a callable with signature `metric

In [76]:
rf.feature_importances_

array([0.11423898, 0.02200886, 0.42727825, 0.4364739 ])

In [77]:
X.drop(columns='sepal_width',inplace=True)
X.head()

,sepal_length,petal_length,petal_width
0,5.1,1.4,0.2
1,4.9,1.4,0.2
2,4.7,1.3,0.2
3,4.6,1.5,0.2
4,5.0,1.4,0.2


In [78]:
rf = RandomForestClassifier()
rf.fit(X,y)

rf.feature_importances_

array([0.17154561, 0.44010048, 0.38835392])

In [79]:
X.drop(columns='sepal_length',inplace=True)
X.head()

,petal_length,petal_width
0,1.4,0.2
1,1.4,0.2
2,1.3,0.2
3,1.5,0.2
4,1.4,0.2


In [80]:
rf = RandomForestClassifier()
rf.fit(X,y)

rf.feature_importances_

array([0.53175704, 0.46824296])

In [81]:
X.drop(columns='petal_length',inplace=True)
X.head()

,petal_width
0,0.2
1,0.2
2,0.2
3,0.2
4,0.2


### Using Sklearn RFE

In [82]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import RFE
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# Load iris dataset
url = "https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv"
df = pd.read_csv(url)

# Separate features and target variable
X = df.drop("species", axis=1)
y = df["species"]

# Initialize RandomForestClassifier
model = RandomForestClassifier()

# Initialize RFE
rfe = RFE(estimator=model, n_features_to_select=1)

# Fit RFE
rfe.fit(X, y)

# Print the ranking
ranking = rfe.ranking_
print("Feature ranking:")

for i, feature in enumerate(X.columns):
    print(f"{feature}: {ranking[i]}")


Feature ranking:
sepal_length: 3
sepal_width: 4
petal_length: 2
petal_width: 1


In [89]:
rfe.support_

array([False, False, False,  True])

In [90]:
X.columns[rfe.support_]

Index(['petal_width'], dtype='str')

### RFECV

In [91]:
from sklearn.feature_selection import RFECV
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

selector = RFECV(
    estimator=model,
    step=1,
    cv=5,
    scoring='accuracy'
)

selector.fit(X, y)

D:\Users\cccc\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


,estimator estimator: ``Estimator`` instanceA supervised learning estimator with a ``fit`` method that providesinformation about feature importance either through a ``coef_``attribute or through a ``feature_importances_`` attribute.,LogisticRegression()
,"cv cv: int, cross-validation generator or an iterable, default=NoneDetermines the cross-validation splitting strategy.Possible inputs for cv are:- None, to use the default 5-fold cross-validation,- integer, to specify the number of folds,- :term:`CV splitter`,- an iterable yielding (train, test) splits as arrays of indices.For integer/None inputs, if ``y`` is binary or multiclass,:class:`~sklearn.model_selection.StratifiedKFold` is used. If theestimator is not a classifier or if ``y`` is neither binary nor multiclass,:class:`~sklearn.model_selection.KFold` is used.Refer :ref:`User Guide <cross_validation>` for the variouscross-validation strategies that can be used here... versionchanged:: 0.22 ``cv`` default value of None changed from 3-fold to 5-fold.",5
,"scoring scoring: str or callable, default=NoneScoring method to evaluate the :class:`RFE` selectors' performance. Options:- str: see :ref:`scoring_string_names` for options.- callable: a scorer callable object (e.g., function) with signature ``scorer(estimator, X, y)``. See :ref:`scoring_callable` for details.- `None`: the `estimator`'s :ref:`default evaluation criterion <scoring_api_overview>` is used.",'accuracy'
,"step step: int or float, default=1If greater than or equal to 1, then ``step`` corresponds to the(integer) number of features to remove at each iteration.If within (0.0, 1.0), then ``step`` corresponds to the percentage(rounded down) of features to remove at each iteration.Note that the last iteration may remove fewer than ``step`` features inorder to reach ``min_features_to_select``.",1
,"min_features_to_select min_features_to_select: int, default=1The minimum number of features to be selected. This number of featureswill always be scored, even if the difference between the originalfeature count and ``min_features_to_select`` isn't divisible by``step``... versionadded:: 0.20",1
,"verbose verbose: int, default=0Controls verbosity of output.",0
,"n_jobs n_jobs: int or None, default=NoneNumber of cores to run in parallel while fitting across folds.``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.``-1`` means using all processors. See :term:`Glossary <n_jobs>`for more details... versionadded:: 0.18",None
,"importance_getter importance_getter: str or callable, default='auto'If 'auto', uses the feature importance either through a `coef_`or `feature_importances_` attributes of estimator.Also accepts a string that specifies an attribute name/pathfor extracting feature importance.For example, give `regressor_.coef_` in case of:class:`~sklearn.compose.TransformedTargetRegressor` or`named_steps.clf.feature_importances_` in case of:class:`~sklearn.pipeline.Pipeline` with its last step named `clf`.If `callable`, overrides the default feature importance getter.The callable is passed with the fitted estimator and it shouldreturn importance for each feature... versionadded:: 0.24",'auto'
Name,Type,Value
"classes_ classes_: ndarray of shape (n_classes,)The classes labels. Only available when `estimator` is a classifier.","ndarray[object](3,)","['setosa','versicolor','virginica']"
"cv_results_ cv_results_: dict of ndarraysAll arrays (values of the dictionary) are sorted in ascending orderby the number of features used (i.e., the first element of the arrayrepresents the models that used the least number of features, while thelast element represents the models that used all available features)... versionadded:: 1.0This dictionary contains the following keys:split(k)_test_score : ndarray of shape (n_subsets_of_features,) The cross-validation scores across (k)th fold.mean_test_score : ndarray of shape (n_subsets_of_features,) Mean of scores over the folds.std_test_score : ndarray of shape (n_subsets_of_features

In [92]:
selector.n_features_

np.int64(4)

In [93]:
X.columns[selector.support_]

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width'], dtype='str')