In [1]:
import numpy as np
from sklearn.datasets import load_diabetes

In [6]:
df = load_diabetes()

In [9]:
x,y = df.data, df.target

In [10]:
x

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

# Using Sklearn LR

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=3)

In [12]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(x_train,y_train)
y_pred = reg.predict(x_test)

from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.4161792211496943

In [13]:
reg.coef_

array([  -1.13744712, -212.8867836 ,  540.45536994,  345.20621542,
       -938.23814645,  516.62060367,  172.85885498,  267.87535242,
        732.63230159,   70.07849485])

In [14]:
reg.intercept_

np.float64(153.13441535285003)

# Making Our Own LR Class

In [15]:
class MeraLR:


    def __init__(self):
        self.coef_ = None
        self.intercept_ = None


    def fit(self,x_train,_train):
        x_train = np.insert(x_train,0,1,axis=1)

        # Calculate The Coeffs
        betas = np.linalg.inv(np.dot(x_train.T,x_train)).dot(x_train.T).dot(y_train)
        self.intercept_ = betas[0]
        self.coef_ = betas[1:]


    def predict(self,x_test):
        y_pred = np.dot(x_test,self.coef_) + self.intercept_
        return y_pred

In [17]:
lr = MeraLR()
lr.fit(x_train,y_train)
y_pred = lr.predict(x_test)

from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.41617922114969363

In [18]:
lr.coef_

array([  -1.13744712, -212.8867836 ,  540.45536994,  345.20621542,
       -938.23814645,  516.62060367,  172.85885498,  267.87535242,
        732.63230159,   70.07849485])

In [19]:
lr.intercept_

np.float64(153.13441535285006)